# **Data Cleaning and Preprocessing**

## Project Overview

Data cleaning and preprocessing are essential steps in data science. Raw datasets may contain missing values, duplicate records, inconsistent formats, or incorrect entries that can affect the quality of analysis.

## Objective

The objective of this project is to clean a dataset by identifying and handling missing values, removing duplicate records, correcting data inconsistencies, and preparing the data for further analysis.

## Tools and Technologies

* Python
* Pandas
* NumPy
* Google Colab

## Expected Outcome

The project will produce a cleaned dataset and demonstrate how data-quality issues can be identified and addressed using Python.

In [1]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

## 2. Create the Sample Dataset

In this step, we create a sample employee dataset using Pandas. The dataset contains information about employee names, ages, cities, salaries, and departments.

We intentionally include missing values, duplicate records, and inconsistent text formatting to demonstrate common data-cleaning techniques.

In [2]:
# Create a sample dataset with data-quality issues

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva',
             'Bob', 'Frank', 'Grace', 'Henry', 'Ivy'],
    'Age': [25, 30, np.nan, 28, 35, 30, 40, 27, np.nan, 29],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Mumbai',
             'Mumbai', 'Delhi', 'Pune', 'Chennai', 'Delhi'],
    'Salary': [30000, 45000, 50000, np.nan, 60000,
               45000, 70000, 35000, 55000, 40000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR',
                   'HR', 'IT', 'Finance', 'IT', 'HR']
}

df = pd.DataFrame(data)

# Introduce inconsistent formats
df.loc[6, 'City'] = ' delhi '
df.loc[7, 'Department'] = 'finance'

# Display the dataset
print("Original Dataset:")
display(df)

Original Dataset:

      Name   Age     City   Salary Department
0    Alice  25.0    Delhi  30000.0         IT
1      Bob  30.0   Mumbai  45000.0         HR
2  Charlie   NaN    Delhi  50000.0         IT
3    David  28.0  Chennai      NaN    Finance
4      Eva  35.0   Mumbai  60000.0         HR
5      Bob  30.0   Mumbai  45000.0         HR
6    Frank  40.0   delhi   70000.0         IT
7    Grace  27.0     Pune  35000.0    finance
8    Henry   NaN  Chennai  55000.0         IT
9      Ivy  29.0    Delhi  40000.0         HR

## 3. Inspect the Dataset

Before cleaning the data, we examine its structure, dimensions, column names, and data types. We also check for missing values and duplicate records.

This initial inspection helps identify data-quality issues that need to be addressed before further analysis.

In [3]:
# Check the dataset dimensions
print("Dataset shape:", df.shape)

# Check column names
print("\nColumn names:")
print(df.columns.tolist())

# Check data types and non-null values
print("\nDataset information:")
df.info()

# Check missing values
print("\nMissing values in each column:")
print(df.isnull().sum())

# Check duplicate rows
print("\nNumber of duplicate rows:", df.duplicated().sum())

Dataset shape: (10, 5)

Column names:
['Name', 'Age', 'City', 'Salary', 'Department']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Age         8 non-null      float64
 2   City        10 non-null     object
 3   Salary      9 non-null      float64
 4   Department  10 non-null     object
dtypes: float64(2), object(3)
memory usage: 532.0+ bytes

Missing values in each column:
Name          0
Age           2
City          0
Salary        1
Department    0
dtype: int64

Number of duplicate rows: 1

## 4. Handle Missing Values

Missing values can affect the accuracy and reliability of data analysis. In this step, we replace missing values in the `Age` and `Salary` columns with their respective median values.

The median is used because it is less sensitive to extreme values than the mean. After replacement, we check the dataset to ensure that no missing values remain.

In [4]:
# Handle missing values using the median

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

# Verify that missing values have been handled
print("Missing values after cleaning:")
print(df.isnull().sum())

print("\nDataset after handling missing values:")
display(df)

Missing values after cleaning:
Name          0
Age           0
City          0
Salary        0
Department    0
dtype: int64

Dataset after handling missing values:

      Name   Age     City   Salary Department
0    Alice  25.0    Delhi  30000.0         IT
1      Bob  30.0   Mumbai  45000.0         HR
2  Charlie  29.5    Delhi  50000.0         IT
3    David  28.0  Chennai  45000.0    Finance
4      Eva  35.0   Mumbai  60000.0         HR
5      Bob  30.0   Mumbai  45000.0         HR
6    Frank  40.0   delhi   70000.0         IT
7    Grace  27.0     Pune  35000.0    finance
8    Henry  29.5  Chennai  55000.0         IT
9      Ivy  29.0    Delhi  40000.0         HR

## 5. Remove Duplicate Records

Duplicate records can lead to inaccurate analysis and misleading results. In this step, we identify and remove duplicate rows using Pandas' `drop_duplicates()` method.

After removing duplicates, we check the dataset again to confirm that no duplicate rows remain.

In [5]:
# Count duplicate rows before removal
print("Duplicate rows before cleaning:", df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Verify duplicate removal
print("Duplicate rows after cleaning:", df.duplicated().sum())

print("\nDataset shape after removing duplicates:", df.shape)

display(df)

Duplicate rows before cleaning: 1
Duplicate rows after cleaning: 0

Dataset shape after removing duplicates: (9, 5)

      Name   Age     City   Salary Department
0    Alice  25.0    Delhi  30000.0         IT
1      Bob  30.0   Mumbai  45000.0         HR
2  Charlie  29.5    Delhi  50000.0         IT
3    David  28.0  Chennai  45000.0    Finance
4      Eva  35.0   Mumbai  60000.0         HR
6    Frank  40.0   delhi   70000.0         IT
7    Grace  27.0     Pune  35000.0    finance
8    Henry  29.5  Chennai  55000.0         IT
9      Ivy  29.0    Delhi  40000.0         HR

## 6. Standardize Text Values

Inconsistent text formatting can cause the same value to be treated as different categories. For example, `delhi`, `Delhi`, and `delhi` may be interpreted as different values.

In this step, we use `strip()` to remove extra spaces and `title()` to standardize capitalization in the `City` and `Department` columns.

In [6]:
# Standardize text formatting in City and Department columns

df['City'] = df['City'].str.strip().str.title()
df['Department'] = df['Department'].str.strip().str.title()

# Display the corrected values
print("Unique cities:", df['City'].unique())
print("Unique departments:", df['Department'].unique())

print("\nDataset after standardizing text:")
display(df)

Unique cities: ['Delhi' 'Mumbai' 'Chennai' 'Pune']
Unique departments: ['It' 'Hr' 'Finance']

Dataset after standardizing text:

      Name   Age     City   Salary Department
0    Alice  25.0    Delhi  30000.0         It
1      Bob  30.0   Mumbai  45000.0         Hr
2  Charlie  29.5    Delhi  50000.0         It
3    David  28.0  Chennai  45000.0    Finance
4      Eva  35.0   Mumbai  60000.0         Hr
6    Frank  40.0    Delhi  70000.0         It
7    Grace  27.0     Pune  35000.0    Finance
8    Henry  29.5  Chennai  55000.0         It
9      Ivy  29.0    Delhi  40000.0         Hr

In [7]:
print("Final Dataset Shape:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:", df.duplicated().sum())

print("\nFinal Cleaned Dataset:")
display(df)

Final Dataset Shape: (9, 5)

Missing Values:
Name          0
Age           0
City          0
Salary        0
Department    0
dtype: int64

Duplicate Rows: 0

Final Cleaned Dataset:

      Name   Age     City   Salary Department
0    Alice  25.0    Delhi  30000.0         It
1      Bob  30.0   Mumbai  45000.0         Hr
2  Charlie  29.5    Delhi  50000.0         It
3    David  28.0  Chennai  45000.0    Finance
4      Eva  35.0   Mumbai  60000.0         Hr
6    Frank  40.0    Delhi  70000.0         It
7    Grace  27.0     Pune  35000.0    Finance
8    Henry  29.5  Chennai  55000.0         It
9      Ivy  29.0    Delhi  40000.0         Hr

In [8]:
df.to_csv('Cleaned_Dataset.csv', index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [9]:
from google.colab import files

files.download('Cleaned_Dataset.csv')

## 7. Conclusion

In this project, we performed data cleaning and preprocessing on a sample employee dataset using Python and Pandas.

The following tasks were completed:

* Inspected the dataset and identified data-quality issues.
* Handled missing values using median imputation.
* Removed duplicate records.
* Standardized text formatting in categorical columns.
* Verified the cleaned dataset to ensure that no missing values or duplicate rows remained.
* Exported the cleaned dataset to a CSV file.

This project demonstrates the importance of data cleaning and preprocessing in preparing reliable data for further analysis and machine learning.